create database customer_behaviour

select top 15 * from customer


--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) [revenue]from customer 
group by gender 

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer 
where discount_applied = 'yes' 
and purchase_amount > (select avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

select top 5 item_purchased,avg(review_rating) [ratings] from customer 
group by item_purchased
order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select avg(purchase_amount)[average amount],shipping_type [coomparison] from customer
group by shipping_type
having shipping_type in ('Standard','Express')



--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select count(customer_id)[total customers],subscription_status,avg(purchase_amount)[avg spend],
sum(purchase_amount)[total revenue] from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select top 5 item_purchased,
100*sum(
    case when discount_applied='yes' then 1 else 0
    end
)  /count(*) as discount_percentage
from customer
group by item_purchased
order by discount_percentage desc


select top 15 * from customer

--Q7. Segment customers into New, Returning, and Loyal based on their total 

    with segment_customer as (
    select previous_purchases,
     case when previous_purchases= 1 then 'new'
     when previous_purchases between 2 and 10 then 'returning'
     else 'loyal'
     end [customer_segment]
     from customer
    )

    select customer_segment,count(*)[customer_type] from segment_customer group by customer_segment
    order by customer_type
--Q8. What are the top 3 most purchased products within each category? 

with items as (
select category, item_purchased, count(customer_id)[total_orders],
ROW_NUMBER() over(partition by category order by count(customer_id) desc)[rnk]
from customer group by category,item_purchased 
)
select  rnk,total_orders,category,item_purchased from items where rnk <= 3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select count(customer_id)[no_of buyers],subscription_status
from customer where previous_purchases >5
group by subscription_status
order by [no_of buyers] desc

--Q10. What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount)[total_revenue] from customer
group by age_group order by total_revenue desc